sudo: required
services:
  - docker

before_install:
  - docker build -t mitulshah96/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mitulshah96/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "appname"
  env: "" 
  bucket_name: ""
  bucket_path: ""
  on:
    branch: master_branch
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"