sudo: required
services:
  - docker

before_install:
  - docker build -t mitulshah96/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mitulshah96/docker-react npm run test -- --coverage
